/**
 * Ant Design 图标映射（ad: 前缀）
 * ---------------------------------------------
 * 供 iconMap 动态渲染使用（后端菜单 icon 字段 / SelectIcon 图标选择）。
 * 键名采用 `ad:` 前缀 + kebab-case。
 *
 * 新增动态图标时在此登记；此处收录常用子集即可，
 * 静态场景直接从 @ant-design/icons 按需导入，无需进表。
 */
import {
  ApartmentOutlined,
  AppstoreOutlined,
  AuditOutlined,
  BarChartOutlined,
  BellOutlined,
  BugOutlined,
  CalendarOutlined,
  CheckOutlined,
  ClockCircleOutlined,
  CloseOutlined,
  CloudOutlined,
  CodeOutlined,
  CopyOutlined,
  DashboardOutlined,
  DatabaseOutlined,
  DeleteOutlined,
  DownloadOutlined,
  EditOutlined,
  EnvironmentOutlined,
  ExportOutlined,
  EyeInvisibleOutlined,
  EyeOutlined,
  FileAddOutlined,
  FileOutlined,
  FileTextOutlined,
  FilterOutlined,
  FolderOpenOutlined,
  FolderOutlined,
  FormOutlined,
  FullscreenExitOutlined,
  FullscreenOutlined,
  GiftOutlined,
  GlobalOutlined,
  HeartOutlined,
  HistoryOutlined,
  HomeFilled,
  ImportOutlined,
  InfoCircleOutlined,
  KeyOutlined,
  LineChartOutlined,
  LinkOutlined,
  LockOutlined,
  LoginOutlined,
  LogoutOutlined,
  MailOutlined,
  MenuOutlined,
  MobileOutlined,
  MoreOutlined,
  NotificationOutlined,
  PieChartOutlined,
  PlusOutlined,
  ProfileOutlined,
  QuestionCircleOutlined,
  ReloadOutlined,
  SafetyCertificateOutlined,
  SafetyOutlined,
  SearchOutlined,
  SettingOutlined,
  ShoppingCartOutlined,
  SortAscendingOutlined,
  SortDescendingOutlined,
  StarOutlined,
  SyncOutlined,
  TableOutlined,
  TeamOutlined,
  ToolOutlined,
  UnlockOutlined,
  UnorderedListOutlined,
  UploadOutlined,
  UserOutlined,
  WalletOutlined,
  WarningOutlined,
} from '@ant-design/icons'
import type { IconComponent } from './index'

const adMap: Record<string, IconComponent> = {
  // 菜单常用
  'ad:home-filled': HomeFilled,
  'ad:setting': SettingOutlined,
  'ad:menu': MenuOutlined,
  'ad:user': UserOutlined,
  'ad:list': UnorderedListOutlined,
  'ad:document': FileTextOutlined,
  // 导航与操作
  'ad:search': SearchOutlined,
  'ad:plus': PlusOutlined,
  'ad:edit': EditOutlined,
  'ad:delete': DeleteOutlined,
  'ad:download': DownloadOutlined,
  'ad:upload': UploadOutlined,
  'ad:refresh': ReloadOutlined,
  'ad:sync': SyncOutlined,
  'ad:close': CloseOutlined,
  'ad:check': CheckOutlined,
  'ad:more': MoreOutlined,
  'ad:filter': FilterOutlined,
  'ad:sort-ascending': SortAscendingOutlined,
  'ad:sort-descending': SortDescendingOutlined,
  'ad:export': ExportOutlined,
  'ad:import': ImportOutlined,
  'ad:copy': CopyOutlined,
  'ad:fullscreen': FullscreenOutlined,
  'ad:fullscreen-exit': FullscreenExitOutlined,
  'ad:logout': LogoutOutlined,
  'ad:login': LoginOutlined,
  // 提示与状态
  'ad:info-circle': InfoCircleOutlined,
  'ad:warning': WarningOutlined,
  'ad:question-circle': QuestionCircleOutlined,
  'ad:eye': EyeOutlined,
  'ad:eye-invisible': EyeInvisibleOutlined,
  // 用户与组织
  'ad:user-group': TeamOutlined,
  'ad:apartment': ApartmentOutlined,
  'ad:profile': ProfileOutlined,
  'ad:audit': AuditOutlined,
  // 数据与图表
  'ad:dashboard': DashboardOutlined,
  'ad:appstore': AppstoreOutlined,
  'ad:table': TableOutlined,
  'ad:bar-chart': BarChartOutlined,
  'ad:line-chart': LineChartOutlined,
  'ad:pie-chart': PieChartOutlined,
  'ad:form': FormOutlined,
  'ad:file': FileOutlined,
  'ad:file-add': FileAddOutlined,
  'ad:folder': FolderOutlined,
  'ad:folder-open': FolderOpenOutlined,
  'ad:database': DatabaseOutlined,
  'ad:cloud': CloudOutlined,
  // 业务与常用
  'ad:bell': BellOutlined,
  'ad:notification': NotificationOutlined,
  'ad:mail': MailOutlined,
  'ad:calendar': CalendarOutlined,
  'ad:clock-circle': ClockCircleOutlined,
  'ad:environment': EnvironmentOutlined,
  'ad:global': GlobalOutlined,
  'ad:safety': SafetyOutlined,
  'ad:safety-certificate': SafetyCertificateOutlined,
  'ad:key': KeyOutlined,
  'ad:lock': LockOutlined,
  'ad:unlock': UnlockOutlined,
  'ad:mobile': MobileOutlined,
  'ad:code': CodeOutlined,
  'ad:bug': BugOutlined,
  'ad:tool': ToolOutlined,
  'ad:shopping-cart': ShoppingCartOutlined,
  'ad:wallet': WalletOutlined,
  'ad:gift': GiftOutlined,
  'ad:star': StarOutlined,
  'ad:heart': HeartOutlined,
  'ad:link': LinkOutlined,
  'ad:history': HistoryOutlined,
}

export default adMap
